/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "Balsa.h"

static ORBitSmallSkeleton get_skel_small_GNOME_Balsa_Composer(POA_GNOME_Balsa_Composer *servant,
const char *opname,gpointer *m_data, gpointer *impl)
{
switch(opname[0]) {
case 'q':
if(strcmp((opname + 1), "ueryInterface")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->queryInterface;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [2];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_queryInterface;
break;
case 'r':
if(strcmp((opname + 1), "ef")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->ref;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_ref;
break;
case 's':
if(strcmp((opname + 1), "endMessage")) break;
*impl = (gpointer)servant->vepv->GNOME_Balsa_Composer_epv->sendMessage;
{ORBit_IInterface *volatile _t_=&GNOME_Balsa_Composer__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_Balsa_Composer_sendMessage;
break;
case 'u':
if(strcmp((opname + 1), "nref")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->unref;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [1];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_unref;
break;
default: break; 
}
return NULL;
}

void POA_GNOME_Balsa_Composer__init(PortableServer_Servant servant,
CORBA_Environment *env)
{
  static PortableServer_ClassInfo class_info = {NULL, (ORBit_small_impl_finder)&get_skel_small_GNOME_Balsa_Composer, "IDL:GNOME/Balsa/Composer:1.0", &GNOME_Balsa_Composer__classid, NULL, &GNOME_Balsa_Composer__iinterface};
  PortableServer_ServantBase__init (       ((PortableServer_ServantBase *)servant), env);
  POA_Bonobo_Unknown__init(servant, env);
   ORBit_skel_class_register (&class_info,
   (PortableServer_ServantBase *)servant, POA_GNOME_Balsa_Composer__fini,
   ORBIT_VEPV_OFFSET (POA_GNOME_Balsa_Composer__vepv, GNOME_Balsa_Composer_epv),
(CORBA_unsigned_long) Bonobo_Unknown__classid,
ORBIT_VEPV_OFFSET (POA_GNOME_Balsa_Composer__vepv, Bonobo_Unknown_epv),
   (CORBA_unsigned_long) 0);}

void POA_GNOME_Balsa_Composer__fini(PortableServer_Servant servant,
CORBA_Environment *env)
{
  POA_Bonobo_Unknown__fini(servant, env);
  PortableServer_ServantBase__fini(servant, env);
}

static ORBitSmallSkeleton get_skel_small_GNOME_Balsa_Application(POA_GNOME_Balsa_Application *servant,
const char *opname,gpointer *m_data, gpointer *impl)
{
switch(opname[0]) {
case 'c':
if(strcmp((opname + 1), "heckmail")) break;
*impl = (gpointer)servant->vepv->GNOME_Balsa_Application_epv->checkmail;
{ORBit_IInterface *volatile _t_=&GNOME_Balsa_Application__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_Balsa_Application_checkmail;
break;
case 'g':
if(strcmp((opname + 1), "etStats")) break;
*impl = (gpointer)servant->vepv->GNOME_Balsa_Application_epv->getStats;
{ORBit_IInterface *volatile _t_=&GNOME_Balsa_Application__iinterface;*m_data = (gpointer)&_t_->methods._buffer [4];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_Balsa_Application_getStats;
break;
case 'o':
switch(opname[1]) {
case 'p':
switch(opname[2]) {
case 'e':
switch(opname[3]) {
case 'n':
switch(opname[4]) {
case 'I':
if(strcmp((opname + 5), "nbox")) break;
*impl = (gpointer)servant->vepv->GNOME_Balsa_Application_epv->openInbox;
{ORBit_IInterface *volatile _t_=&GNOME_Balsa_Application__iinterface;*m_data = (gpointer)&_t_->methods._buffer [3];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_Balsa_Application_openInbox;
break;
case 'M':
if(strcmp((opname + 5), "ailbox")) break;
*impl = (gpointer)servant->vepv->GNOME_Balsa_Application_epv->openMailbox;
{ORBit_IInterface *volatile _t_=&GNOME_Balsa_Application__iinterface;*m_data = (gpointer)&_t_->methods._buffer [1];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_Balsa_Application_openMailbox;
break;
case 'U':
if(strcmp((opname + 5), "nread")) break;
*impl = (gpointer)servant->vepv->GNOME_Balsa_Application_epv->openUnread;
{ORBit_IInterface *volatile _t_=&GNOME_Balsa_Application__iinterface;*m_data = (gpointer)&_t_->methods._buffer [2];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_Balsa_Application_openUnread;
break;
default: break; 
}
break;
default: break; 
}
break;
default: break; 
}
break;
default: break; 
}
break;
case 'q':
if(strcmp((opname + 1), "ueryInterface")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->queryInterface;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [2];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_queryInterface;
break;
case 'r':
if(strcmp((opname + 1), "ef")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->ref;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_ref;
break;
case 'u':
if(strcmp((opname + 1), "nref")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->unref;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [1];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_unref;
break;
default: break; 
}
return NULL;
}

void POA_GNOME_Balsa_Application__init(PortableServer_Servant servant,
CORBA_Environment *env)
{
  static PortableServer_ClassInfo class_info = {NULL, (ORBit_small_impl_finder)&get_skel_small_GNOME_Balsa_Application, "IDL:GNOME/Balsa/Application:1.0", &GNOME_Balsa_Application__classid, NULL, &GNOME_Balsa_Application__iinterface};
  PortableServer_ServantBase__init (       ((PortableServer_ServantBase *)servant), env);
  POA_Bonobo_Unknown__init(servant, env);
   ORBit_skel_class_register (&class_info,
   (PortableServer_ServantBase *)servant, POA_GNOME_Balsa_Application__fini,
   ORBIT_VEPV_OFFSET (POA_GNOME_Balsa_Application__vepv, GNOME_Balsa_Application_epv),
(CORBA_unsigned_long) Bonobo_Unknown__classid,
ORBIT_VEPV_OFFSET (POA_GNOME_Balsa_Application__vepv, Bonobo_Unknown_epv),
   (CORBA_unsigned_long) 0);}

void POA_GNOME_Balsa_Application__fini(PortableServer_Servant servant,
CORBA_Environment *env)
{
  POA_Bonobo_Unknown__fini(servant, env);
  PortableServer_ServantBase__fini(servant, env);
}

