/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "Balsa.h"

void GNOME_Balsa_Composer_sendMessage(GNOME_Balsa_Composer _obj, const CORBA_char * from, const CORBA_char * to, const CORBA_char * cc, const CORBA_char * subject, const GNOME_Balsa_Composer_attachs* attachments, const CORBA_boolean nogui, CORBA_Environment *ev){
gpointer _args[6];
_args[0] = (gpointer)&from;
_args[1] = (gpointer)&to;
_args[2] = (gpointer)&cc;
_args[3] = (gpointer)&subject;
_args[4] = (gpointer)attachments;
_args[5] = (gpointer)&nogui;
ORBit_c_stub_invoke (_obj, &GNOME_Balsa_Composer__iinterface.methods, 0, NULL, _args, NULL, ev, GNOME_Balsa_Composer__classid, G_STRUCT_OFFSET (POA_GNOME_Balsa_Composer__epv, sendMessage),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_Balsa_Composer_sendMessage);

}
void GNOME_Balsa_Application_checkmail(GNOME_Balsa_Application _obj, CORBA_Environment *ev){
ORBit_c_stub_invoke (_obj, &GNOME_Balsa_Application__iinterface.methods, 0, NULL, NULL, NULL, ev, GNOME_Balsa_Application__classid, G_STRUCT_OFFSET (POA_GNOME_Balsa_Application__epv, checkmail),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_Balsa_Application_checkmail);

}
void GNOME_Balsa_Application_openMailbox(GNOME_Balsa_Application _obj, const CORBA_char * name, CORBA_Environment *ev){
gpointer _args[1];
_args[0] = (gpointer)&name;
ORBit_c_stub_invoke (_obj, &GNOME_Balsa_Application__iinterface.methods, 1, NULL, _args, NULL, ev, GNOME_Balsa_Application__classid, G_STRUCT_OFFSET (POA_GNOME_Balsa_Application__epv, openMailbox),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_Balsa_Application_openMailbox);

}
void GNOME_Balsa_Application_openUnread(GNOME_Balsa_Application _obj, CORBA_Environment *ev){
ORBit_c_stub_invoke (_obj, &GNOME_Balsa_Application__iinterface.methods, 2, NULL, NULL, NULL, ev, GNOME_Balsa_Application__classid, G_STRUCT_OFFSET (POA_GNOME_Balsa_Application__epv, openUnread),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_Balsa_Application_openUnread);

}
void GNOME_Balsa_Application_openInbox(GNOME_Balsa_Application _obj, CORBA_Environment *ev){
ORBit_c_stub_invoke (_obj, &GNOME_Balsa_Application__iinterface.methods, 3, NULL, NULL, NULL, ev, GNOME_Balsa_Application__classid, G_STRUCT_OFFSET (POA_GNOME_Balsa_Application__epv, openInbox),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_Balsa_Application_openInbox);

}
void GNOME_Balsa_Application_getStats(GNOME_Balsa_Application _obj, CORBA_long* unread, CORBA_long* unsent, CORBA_Environment *ev){
gpointer _args[2];
_args[0] = &unread;
_args[1] = &unsent;
ORBit_c_stub_invoke (_obj, &GNOME_Balsa_Application__iinterface.methods, 4, NULL, _args, NULL, ev, GNOME_Balsa_Application__classid, G_STRUCT_OFFSET (POA_GNOME_Balsa_Application__epv, getStats),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_Balsa_Application_getStats);

}
