/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#define ORBIT_IDL_C_COMMON
#define Balsa_COMMON
#include "Balsa.h"

static const CORBA_unsigned_long ORBit_zero_int = 0;

#ifndef ORBIT_IDL_C_IMODULE_Balsa
void _ORBIT_skel_small_GNOME_Balsa_Composer_sendMessage(POA_GNOME_Balsa_Composer             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_sendMessage)(PortableServer_Servant _servant, const CORBA_char * from, const CORBA_char * to, const CORBA_char * cc, const CORBA_char * subject, const GNOME_Balsa_Composer_attachs* attachments, const CORBA_boolean nogui, CORBA_Environment *ev)) {
_impl_sendMessage (_o_servant, *(const CORBA_char * *)_o_args[0], *(const CORBA_char * *)_o_args[1], *(const CORBA_char * *)_o_args[2], *(const CORBA_char * *)_o_args[3], (const CORBA_sequence_CORBA_string*)_o_args[4], *(const CORBA_boolean *)_o_args[5], _o_ev);
}
void _ORBIT_skel_small_GNOME_Balsa_Application_checkmail(POA_GNOME_Balsa_Application             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_checkmail)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
_impl_checkmail (_o_servant, _o_ev);
}
void _ORBIT_skel_small_GNOME_Balsa_Application_openMailbox(POA_GNOME_Balsa_Application             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_openMailbox)(PortableServer_Servant _servant, const CORBA_char * name, CORBA_Environment *ev)) {
_impl_openMailbox (_o_servant, *(const CORBA_char * *)_o_args[0], _o_ev);
}
void _ORBIT_skel_small_GNOME_Balsa_Application_openUnread(POA_GNOME_Balsa_Application             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_openUnread)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
_impl_openUnread (_o_servant, _o_ev);
}
void _ORBIT_skel_small_GNOME_Balsa_Application_openInbox(POA_GNOME_Balsa_Application             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_openInbox)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
_impl_openInbox (_o_servant, _o_ev);
}
void _ORBIT_skel_small_GNOME_Balsa_Application_getStats(POA_GNOME_Balsa_Application             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_getStats)(PortableServer_Servant _servant, CORBA_long* unread, CORBA_long* unsent, CORBA_Environment *ev)) {
_impl_getStats (_o_servant, *(CORBA_long* *)_o_args[0], *(CORBA_long* *)_o_args[1], _o_ev);
}

#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'a') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static ORBIT2_MAYBE_CONST CORBA_TypeCode anon_subtypes_array1[] = {(CORBA_TypeCode)&TC_CORBA_string_struct};
#ifdef ORBIT_IDL_C_IMODULE_Balsa
static
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_sequence,
0,
0,
MAX (ORBIT_ALIGNOF_CORBA_POINTER, MAX (ORBIT_ALIGNOF_CORBA_LONG, MAX (ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
0,
1
,
(CORBA_TypeCode *)anon_subtypes_array1,
CORBA_OBJECT_NIL,
NULL,
NULL,
NULL,
NULL,
-1,
0,
0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_CORBA_string_0 == 'B') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_2 == 'l') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_3 == 's') \
&& (TC_IMPL_TC_CORBA_sequence_CORBA_string_4 == 'a') \
) && !defined(TC_DEF_TC_CORBA_sequence_CORBA_string)
#define TC_DEF_TC_CORBA_sequence_CORBA_string 1
static ORBIT2_MAYBE_CONST CORBA_TypeCode anon_subtypes_array8[] = {(CORBA_TypeCode)&TC_CORBA_string_struct};
#ifdef ORBIT_IDL_C_IMODULE_Balsa
static
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_CORBA_sequence_CORBA_string_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_sequence,
0,
0,
MAX (ORBIT_ALIGNOF_CORBA_POINTER, MAX (ORBIT_ALIGNOF_CORBA_LONG, MAX (ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
0,
1
,
(CORBA_TypeCode *)anon_subtypes_array8,
CORBA_OBJECT_NIL,
NULL,
NULL,
NULL,
NULL,
-1,
0,
0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Balsa_Composer_attachs_0 == 'B') \
&& (TC_IMPL_TC_GNOME_Balsa_Composer_attachs_1 == 'a') \
&& (TC_IMPL_TC_GNOME_Balsa_Composer_attachs_2 == 'l') \
&& (TC_IMPL_TC_GNOME_Balsa_Composer_attachs_3 == 's') \
&& (TC_IMPL_TC_GNOME_Balsa_Composer_attachs_4 == 'a') \
) && !defined(TC_DEF_TC_GNOME_Balsa_Composer_attachs)
#define TC_DEF_TC_GNOME_Balsa_Composer_attachs 1
static ORBIT2_MAYBE_CONST CORBA_TypeCode anon_subtypes_array11[] = {(CORBA_TypeCode)&TC_CORBA_sequence_CORBA_string_struct};
#ifdef ORBIT_IDL_C_IMODULE_Balsa
static
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_GNOME_Balsa_Composer_attachs_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_alias,
0,
0,
MAX (ORBIT_ALIGNOF_CORBA_POINTER, MAX (ORBIT_ALIGNOF_CORBA_LONG, MAX (ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
0,
1
,
(CORBA_TypeCode *)anon_subtypes_array11,
CORBA_OBJECT_NIL,
(char *)"attachs",
(char *)"IDL:GNOME/Balsa/Composer/attachs:1.0",
NULL,
NULL,
-1,
0,
0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Balsa_Composer_0 == 'B') \
&& (TC_IMPL_TC_GNOME_Balsa_Composer_1 == 'a') \
&& (TC_IMPL_TC_GNOME_Balsa_Composer_2 == 'l') \
&& (TC_IMPL_TC_GNOME_Balsa_Composer_3 == 's') \
&& (TC_IMPL_TC_GNOME_Balsa_Composer_4 == 'a') \
) && !defined(TC_DEF_TC_GNOME_Balsa_Composer)
#define TC_DEF_TC_GNOME_Balsa_Composer 1
#ifdef ORBIT_IDL_C_IMODULE_Balsa
static
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_GNOME_Balsa_Composer_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_objref,
0,
0,
ORBIT_ALIGNOF_CORBA_POINTER,
0,
0
,
NULL,
CORBA_OBJECT_NIL,
(char *)"Composer",
(char *)"IDL:GNOME/Balsa/Composer:1.0",
NULL,
NULL,
-1,
0,
0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_Balsa_Application_0 == 'B') \
&& (TC_IMPL_TC_GNOME_Balsa_Application_1 == 'a') \
&& (TC_IMPL_TC_GNOME_Balsa_Application_2 == 'l') \
&& (TC_IMPL_TC_GNOME_Balsa_Application_3 == 's') \
&& (TC_IMPL_TC_GNOME_Balsa_Application_4 == 'a') \
) && !defined(TC_DEF_TC_GNOME_Balsa_Application)
#define TC_DEF_TC_GNOME_Balsa_Application 1
#ifdef ORBIT_IDL_C_IMODULE_Balsa
static
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_GNOME_Balsa_Application_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_objref,
0,
0,
ORBIT_ALIGNOF_CORBA_POINTER,
0,
0
,
NULL,
CORBA_OBJECT_NIL,
(char *)"Application",
(char *)"IDL:GNOME/Balsa/Application:1.0",
NULL,
NULL,
-1,
0,
0, 0
};
#endif

#ifndef ORBIT_IDL_C_IMODULE_Balsa
CORBA_unsigned_long GNOME_Balsa_Composer__classid = 0;
#endif

#ifndef ORBIT_IDL_C_IMODULE_Balsa
CORBA_unsigned_long GNOME_Balsa_Application__classid = 0;
#endif

/* Interface type data */

static ORBit_IArg GNOME_Balsa_Composer_sendMessage__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"from" },
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"to" },
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"cc" },
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"subject" },
	{ TC_GNOME_Balsa_Composer_attachs,  ORBit_I_ARG_IN , (char *)"attachments" },
	{ TC_CORBA_boolean,  ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, (char *)"nogui" }
};

#ifdef ORBIT_IDL_C_IMODULE_Balsa
static
#endif
ORBit_IMethod GNOME_Balsa_Composer__imethods [] = {
	{
		{ 6, 6, GNOME_Balsa_Composer_sendMessage__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"sendMessage", 11,
		0
}
};

static CORBA_string GNOME_Balsa_Composer__base_itypes[] = {
(char *)"IDL:Bonobo/Unknown:1.0",
(char *)"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef ORBIT_IDL_C_IMODULE_Balsa
static
#endif
ORBit_IInterface GNOME_Balsa_Composer__iinterface = {
TC_GNOME_Balsa_Composer,{1, 1, GNOME_Balsa_Composer__imethods, FALSE},
{2, 2, GNOME_Balsa_Composer__base_itypes, FALSE}
};

static ORBit_IArg GNOME_Balsa_Application_openMailbox__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"name" }
};
static ORBit_IArg GNOME_Balsa_Application_getStats__arginfo [] = {
	{ TC_CORBA_long,  ORBit_I_ARG_OUT | ORBit_I_COMMON_FIXED_SIZE, (char *)"unread" },
	{ TC_CORBA_long,  ORBit_I_ARG_OUT | ORBit_I_COMMON_FIXED_SIZE, (char *)"unsent" }
};

#ifdef ORBIT_IDL_C_IMODULE_Balsa
static
#endif
ORBit_IMethod GNOME_Balsa_Application__imethods [] = {
	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"checkmail", 9,
		0
}
, 	{
		{ 1, 1, GNOME_Balsa_Application_openMailbox__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"openMailbox", 11,
		0
}
, 	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"openUnread", 10,
		0
}
, 	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"openInbox", 9,
		0
}
, 	{
		{ 2, 2, GNOME_Balsa_Application_getStats__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"getStats", 8,
		0
}
};

static CORBA_string GNOME_Balsa_Application__base_itypes[] = {
(char *)"IDL:Bonobo/Unknown:1.0",
(char *)"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef ORBIT_IDL_C_IMODULE_Balsa
static
#endif
ORBit_IInterface GNOME_Balsa_Application__iinterface = {
TC_GNOME_Balsa_Application,{5, 5, GNOME_Balsa_Application__imethods, FALSE},
{2, 2, GNOME_Balsa_Application__base_itypes, FALSE}
};

